[2025-02-04T22:03:26.880+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-04T22:03:26.897+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Temp_elt_postgres.extract_weather_data manual__2025-02-04T22:03:19.645361+00:00 [queued]>
[2025-02-04T22:03:26.913+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Temp_elt_postgres.extract_weather_data manual__2025-02-04T22:03:19.645361+00:00 [queued]>
[2025-02-04T22:03:26.914+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-04T22:03:26.980+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_weather_data> on 2025-02-04 22:03:19.645361+00:00
[2025-02-04T22:03:26.989+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'Temp_elt_postgres', 'extract_weather_data', 'manual__2025-02-04T22:03:19.645361+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_postgres.py', '--cfg-path', '/tmp/tmp5qev1m6t']
[2025-02-04T22:03:26.992+0000] {standard_task_runner.py:105} INFO - Job 84: Subtask extract_weather_data
[2025-02-04T22:03:26.995+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=917) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-04T22:03:26.997+0000] {standard_task_runner.py:72} INFO - Started process 927 to run task
[2025-02-04T22:03:27.113+0000] {task_command.py:467} INFO - Running <TaskInstance: Temp_elt_postgres.extract_weather_data manual__2025-02-04T22:03:19.645361+00:00 [running]> on host c95ac323e145
[2025-02-04T22:03:27.220+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Temp_elt_postgres' AIRFLOW_CTX_TASK_ID='extract_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-04T22:03:19.645361+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-04T22:03:19.645361+00:00'
[2025-02-04T22:03:27.222+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-04T22:03:27.925+0000] {logging_mixin.py:190} INFO - {'message': 'Too many requests'}
[2025-02-04T22:03:27.933+0000] {logging_mixin.py:190} INFO -              message
0  Too many requests
[2025-02-04T22:03:27.934+0000] {logging_mixin.py:190} INFO - undexpected error: {e}
[2025-02-04T22:03:27.935+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-04T22:03:27.944+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-04T22:03:27.945+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Temp_elt_postgres, task_id=extract_weather_data, run_id=manual__2025-02-04T22:03:19.645361+00:00, execution_date=20250204T220319, start_date=20250204T220326, end_date=20250204T220327
[2025-02-04T22:03:28.007+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-04T22:03:28.121+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-04T22:03:28.136+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
