[2025-01-03T21:34:03.048+0100] {processor.py:186} INFO - Started process (PID=79608) to work on /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-03T21:34:03.053+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-03T21:34:03.055+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:34:03.055+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-03T21:34:03.132+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:34:03.120+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-03T21:34:03.132+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:34:03.132+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-03T21:34:03.132+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-03T21:34:03.261+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.221 seconds
[2025-01-03T21:37:56.617+0100] {processor.py:186} INFO - Started process (PID=81621) to work on /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-03T21:37:56.621+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-03T21:37:56.622+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:37:56.622+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-03T21:37:56.684+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:37:56.679+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-03T21:37:56.684+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:37:56.684+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-03T21:37:56.684+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-03T21:37:56.805+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.196 seconds
[2025-01-03T21:41:04.417+0100] {processor.py:186} INFO - Started process (PID=83321) to work on /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-03T21:41:04.422+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-03T21:41:04.423+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:41:04.422+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-03T21:41:04.481+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:41:04.475+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-03T21:41:04.481+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:41:04.481+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-03T21:41:04.481+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-03T21:41:04.607+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.197 seconds
[2025-01-03T21:44:09.106+0100] {processor.py:186} INFO - Started process (PID=84441) to work on /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-03T21:44:09.111+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-03T21:44:09.112+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:44:09.112+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-03T21:44:09.168+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:44:09.163+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-03T21:44:09.169+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:44:09.168+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-03T21:44:09.169+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-03T21:44:09.288+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.189 seconds
[2025-01-03T21:47:18.892+0100] {processor.py:186} INFO - Started process (PID=86079) to work on /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-03T21:47:18.897+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-03T21:47:18.898+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:47:18.897+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-03T21:47:19.014+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:47:19.002+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-03T21:47:19.015+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:47:19.015+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-03T21:47:19.016+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-03T21:47:19.239+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.355 seconds
[2025-01-03T21:50:32.807+0100] {processor.py:186} INFO - Started process (PID=87179) to work on /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-03T21:50:32.811+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-03T21:50:32.814+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:50:32.813+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-03T21:50:32.878+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:50:32.873+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-03T21:50:32.879+0100] {logging_mixin.py:190} INFO - [2025-01-03T21:50:32.879+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-03T21:50:32.879+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-03T21:50:33.009+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow_venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.210 seconds
